[book]
authors = ["Denys Vuika"]
language = "en"
multilingual = false
src = "docs"
title = "WebStencils SDK"

[output.html]
git-repository-url = "https://github.com/webstencils/sdk"
site-url = "/sdk/"
